### ISSUE TITLE
TabBar viewconroller problem

### ISSUE THREAD

**Issue by qx** [JanGorman/Agrume#10]
if you embed navigation conroller into a tabbar, the image show with agrume will present tabbar view, even in a deep navigation stack.

**Comment by jakecraige** [comment]
Seeing a similar issue, probably the same one, where there's a flicker of a the VC lower in the stack when dismissing.

Tracked it down to [here](https://github.com/JanGorman/Agrume/blob/1792149aeb6bc68da7be5ef5be676f74d0e01158/Agrume/Agrume.swift#L188). It's taking a snapshot of the root view controller, rather than the visible view controller, or the one I passed in.

So if my heiarchy is `UITableViewController -> UIViewController` and I call `showFrom` with the `UIViewController`, I'll see a flicker of the `UITableViewController` because of that line above.

**Comment by JanGorman** [comment]
Fixed with #26 👏
