### ISSUE TITLE
1st image is having issue while loading RTL (Right To Left) support

### ISSUE THREAD

**Issue by hariprasaad** [JanGorman/Agrume#182]
The image which is getting loaded as 1st is showing up only in the half screen.
Attaching image for reference.
![Arabic](https://user-images.githubusercontent.com/33032764/79108327-be06c280-7d93-11ea-8127-c4d772675814.png)
![English](https://user-images.githubusercontent.com/33032764/79108373-d5de4680-7d93-11ea-88ec-d553a6cf62a9.png)

**Comment by JanGorman** [comment]
Thanks for reporting. I'm able to reproduce the bug. I don't have an immediate idea where the issue could lie but will investigate.

**Comment by JanGorman** [comment]
This was a strange one. It's fixed by wrapping the collection view that Agrume uses into a container view. During presentation the view is "zoomed" in by applying an affine transform and this transform was what broke the display. Transform the container view fixed it https://github.com/JanGorman/Agrume/blob/master/Agrume/Agrume.swift#L304

Some UIKit oddness or bug
