### ISSUE TITLE
Argume view controller not deallocated

### ISSUE THREAD

**Issue by gunnarblom** [JanGorman/Agrume#23]
The only code I have is:

```swift
if let image = UIImage(named: "image.png") {
    let agrume = Agrume(image: image)
    agrume.showFrom(self)
}
```

And when showing the image, the memory increases 100mb. But when I dismiss it it doesn't give back the memory. When debugging, the Argume view controller isn't deallocated (deinit is never run).

I've tried removing delegate/datasource from collection view on dismiss, but it doesn't help. Haven't found the reason.

**Comment by JanGorman** [comment]
I've drilled it down to two areas, one being `viewController.presentViewController(self, …)` and the other the call to `collectionView.performBatchUpdates`. No solution yet as none of my tests with `weak`/`unowned` references have been able to resolve this. Will post more if I find something else.

**Comment by JanGorman** [comment]
Xcode 8's memory debugger FTW. Although it did not recognise this as a cycle: The cell's used to display images was passed two closures, one to handle dismissing by tap, the other by flicking the image. And since I passed those in as function references from Agrume itself it retained them. Which came as a bit as a surprise but lesson learnt.
