### ISSUE TITLE
Remove or update SwiftyGif submodule.

### ISSUE THREAD

**Issue by lukeredpath** [JanGorman/Agrume#308]
The SwiftyGif repo used to contain a lot of large snapshot test images which makes it *very* slow to install Agrume via SPM over a slow internet connection while Xcode clones the Agrume repo.

The submodule serves no purpose if you're using SPM, however if there is a reason for having this please consider bumping the commit that the submodule points at to a more recent version of SwiftyGif as the large snapshot files were removed in this commit https://github.com/kirualex/SwiftyGif/commit/c804e36ea21f25715a55216ff40d18c3941f8ced

**Comment by JanGorman** [comment]
Thanks for the report! TBH I wasn't aware that SPM clones the submodule. The submodule really only is there for local development since the project supports CocoaPods and Carthage as well and I didn't want to rely on either for local development but it's probably time to revisit that decision. I'll try to get around to it in the coming days but of course you're welcome to submit a PR as well if it's urgent.

**Comment by JanGorman** [comment]
Updated in https://github.com/JanGorman/Agrume/releases/tag/5.8.1

**Comment by lukeredpath** [comment]
@JanGorman thanks for updating this - just looking at this again and I'm not 100% sure this will fix the problem because I don't think submodules are shallow-cloned by default.

However git does support this by adding "shallow = true" to the gitmodules config, e.g.:

```
[submodule "Frameworks/SwiftyGif"]
	path = Frameworks/SwiftyGif
	url = https://github.com/kirualex/SwiftyGif
	shallow = true
```
