### ISSUE TITLE
Why would my uinavigationbar disappear on show?

### ISSUE THREAD

**Issue by tamoyal** [JanGorman/Agrume#54]
My UI navigation bar disappears when the image is shown. It's not hidden, it literally disappears and then when I show the view again it appears but the view jumps since the component is coming back in with no animation. This doesn't happen with a few other libraries I've tried such as https://github.com/hyperoslo/Lightbox and I also looked through your source code to see if it had to do with the way you were presenting the view controller or something else obvious and I don't see anything. Any hunches?

**Comment by JanGorman** [comment]
Hey,

Thanks for the report. Well… as you say, there's nothing special going with the presentation since it just calls `viewController.present(self, animated: false)` on the controller that's passed in by the `showFrom()` method. Issue #51 also mentions a jumping when you dismiss the image again so they could be related.

Can you share a code snippet of how you're initialising Agrume and presenting images?

**Comment by tamoyal** [comment]
I'm not doing anything fancy when showing. Copied and pasted from your example. I'll try to put together a sample project but it may take some time.

**Comment by Alexookah** [comment]
@JanGorman 
this is also a very old issue. I don't think this no longer exists.
Could @tamoyal report if this issue exists in the latest release?
