### ISSUE TITLE
Rotation changes the current Index of the image

### ISSUE THREAD

**Issue by Daxito** [JanGorman/Agrume#77]
I noticed that when I rotate from Portrait to Landscape say Image at Index 3, landscape shows image at index 2 instead of 3, then I rotate back to Portrait and it now displays the correct image (index 3)

**Comment by JanGorman** [comment]
Hey thanks for the report – there's an ongoing [refactoring branch](https://github.com/JanGorman/Agrume/tree/the-5.0) and I'll keep an eye out for this bug there but since it switches away from using a UICollectionView under the hood this should be solved by itself. I'll update this ticket once it's merged back

**Comment by Daxito** [comment]
Thank you @JanGorman !

**Comment by musbaalbaki** [comment]
+1

**Comment by musbaalbaki** [comment]
Any update on this please?
